### Numpy 

- Most important package in python for numerical computations.
- Uses in data science/ML/AI


### What is Numpy have: 
- Provides a high-performance multidimensional array object, and tools for working with these arrays
- use for computing scientific/mathematical data like matrix computations,linear algebra,numerical analysis etc

In [14]:
##import the library 
import numpy as np

In [15]:
##create a array in numpy
a=np.array([1,2,3,4,5])
print(a)

print(np.arange(10))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


### why numpy is useful 
- memory-efficient and provides fast numerical operations

In [16]:
#python list
lis=range(500)
%timeit [i**2 for i in lis]

154 µs ± 505 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
#numpy array
a=np.arange(500)
%timeit a**2

930 ns ± 4.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### creation of different dimension arrays

In [23]:
## 1-D/vector

a=np.array([0,1,2,3,4,])

#print the array
print(a)

#check array dimension
print(a.ndim)

#shape of array
print(a.shape)

#length of array
print(len(a))


[0 1 2 3 4]
1
(5,)
5


In [28]:
# 2-D array/matrix

b=np.array([[1,2,3,4],[5,6,7,8]])

#print the array
print(b)

#check array dimension
print(b.ndim)

#shape of array
print(b.shape)

#length of array
print(len(b))  #gives the no. of rows



[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
2


In [30]:
## n -D array/tensor

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(c)

#check array dimension
print(c.ndim)

#shape of array
print(c.shape)



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


In [50]:
## arange function

a=np.arange(5)
print(a)
print(a.dtype)

###if want float number array

a1=np.arange(5,dtype='float64')
print(a1)
print(a1.dtype)


b=np.arange(1,15,2)#start,end(not included),step
print(b)




[0 1 2 3 4]
int32
[0. 1. 2. 3. 4.]
float64
[ 1  3  5  7  9 11 13]


In [36]:
## linspace function/linear space

a=np.linspace(0,1,5) #start,end,no. of points with equal space 
print(a)


[0.   0.25 0.5  0.75 1.  ]


In [37]:
### zeros and ones function
### create a matrix full of zeroes or ones using np.zeros and np.one commands respectively

a=np.zeros((2,2))
print(a)

b=np.ones((2,2))
print(b)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [41]:
## identity matrix

a=np.eye(2)
print(a)

## diagonal array with any number

b=np.diag([1,2,3,4,5])
print(b)

[[1. 0.]
 [0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [45]:
#### array with random number
###uniformal distribution random number 

a=np.random.rand(2,3) #size
a




array([[0.98704177, 0.77210602, 0.74970009],
       [0.96098164, 0.02373972, 0.6994066 ]])

### Indexing 

In [51]:
a=np.arange(10)
print(a[5]) #indics start at 0


5


In [53]:
a=np.array([[1,2,3],[3,2,1]])
print(a)

[[1 2 3]
 [3 2 1]]


In [54]:
##assigning new value
a[1,1]=100
a

array([[  1,   2,   3],
       [  3, 100,   1]])

### Slicing

In [57]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
###sub array using slicing

print(a[1:5])
print('-'*10)
print(a[1:8:2])# [start :end(last is not included):step]

[1 2 3 4]
----------
[1 3 5 7]


In [64]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [65]:
b=np.arange(5)
print(b[::-1])

print('-'*10)
a[5:]=b[::-1]
print(a)

[4 3 2 1 0]
----------
[0 1 2 3 4 4 3 2 1 0]


### copies and views



In [66]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [69]:
### two array sharing the memory using views

np.shares_memory(a,b)

True

In [70]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [72]:
#### when b modified b ,a also changes beocz both are sharing the same memory
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [74]:
a=np.arange(10)

a1=a[::2].copy()
a1

array([0, 2, 4, 6, 8])

In [76]:
### two array  not sharing memory
np.shares_memory(a,a1)

False

### Indexing with an array of intergers

In [77]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [82]:
##new value aggigned at these index
a[[2,4,5]]=-500
a

array([   0,   10, -500,   30, -500, -500,   60,   70,   80,   90])

### Operations

In [84]:
a=np.arange(5)## element wise 
a+5

array([5, 6, 7, 8, 9])

#### arithmatic operation

In [86]:
b=np.array([1,1,1,1,1])
a-b

array([-1,  0,  1,  2,  3])

In [88]:
a*(b+2)

array([ 0,  3,  6,  9, 12])

In [95]:

m=np.array([[1,2],[3,4]])
print(m)
print("-"*10)

print(m*m)  ## element wise multiplication
print("-"*10)
print(m.dot(m)) ## matrix multiplication


[[1 2]
 [3 4]]
----------
[[ 1  4]
 [ 9 16]]
----------
[[ 7 10]
 [15 22]]


#### comparison operation



In [106]:
a=np.array([1,2,3,4])
b=np.array([3,2,2,4])

print(a==b)
print(a>b)

[False  True False  True]
[False False  True False]


#### logical operations

In [107]:
a=np.array([0,1,0,1],dtype=bool)
b=np.array([0,0,1,1],dtype='bool')
print(a.dtype)
print(np.logical_xor(a,b))

bool
[False  True  True False]


### Basic reductions


In [108]:
##computing sum

x=np.array([1,2,3,4])
print(np.sum(x))

10


In [109]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [114]:
### column wise sum
print(np.sum(x,axis=0))
print('----------')
### row wise sum
print(np.sum(x,axis=1))

[3 3]
----------
[2 4]


In [117]:
###min ,max function

x=np.array([1,3,2])

print(x.max(),"is maximum number in array at the index ",x.argmax())
print(x.min(),"is minimum number in array at the index ",x.argmin())



3 is maximum number in array at the index  1
1 is minimum number in array at the index  0


#### logical operations

In [118]:
np.all([True,True,False])


False

In [119]:
np.any([True,True,False])

True

#### stastistics

In [121]:
x=np.array([1,2,3,1])

print(x.mean())
print(np.median(x))
print(x.std())

1.75
1.5
0.82915619758885


#### example

In [123]:
#load data into numpy array object
data = np.loadtxt('population.txt')

In [124]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [126]:
year,hares,lynxes,carrot=data.T ##columns to variables

In [128]:
new_data=data[:,1:]
new_data

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [130]:
### some operation
new_data.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

### Broadcasting

In [144]:
a=np.tile(np.arange(0,40,10),(3,1)) #####tile the same data in 3 rows
print(a)
print(a.shape)
print('-'* 30)

####transpose
a=a.T
print(a)


[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
(3, 4)
------------------------------
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [145]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [146]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [150]:
a=np.arange(0,40,10)
a.shape

(4,)

In [151]:
#### from broadcasting we will convert a to 2-d array

a=a[:,np.newaxis]
print(a)
print(a.shape)

[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [152]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### array shape manipulation

In [155]:
## Flattening

a=np.array([[1,2,3],[4,5,6]])
print(a)
print('-'*40)
print(a.ravel())

[[1 2 3]
 [4 5 6]]
----------------------------------------
[1 2 3 4 5 6]


In [160]:
### reshaping it again after flattening

b=a.ravel()
print(b)
print('-'*40)
print(b.reshape((2,3)))####(size which we want)

[1 2 3 4 5 6]
----------------------------------------
[[1 2 3]
 [4 5 6]]


### sorting

In [162]:
a=np.array([[8,2,3],[15,7,20]])

b=np.sort(a,axis=1)
b

array([[ 2,  3,  8],
       [ 7, 15, 20]])